spring.application.name=hsaorafael.crm
spring.datasource.url=jdbc:postgresql://localhost:5432/crm-saorafael
spring.datasource.username=postgres
spring.datasource.password=Ar*274227
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=update


